### ISSUE TITLE
Plugin broken due to missing shapely module in QGIS 2.18.17 (OSGeo4W network installation)

### ISSUE THREAD

**Issue by SteveLowman** [peetw/GeometryValidator#2]
Previously I have used the plugin with no problems in a standalone application of QGIS 2.18.17.
Today, I uninstalled the standalone application, and installed instead from the OSGeo4W network installer.

Unfortunately, now I get the error message that the shapely module is missing, and the plugin is broken.
Colleagues using the standalone application still have no such problem.

The traceback text is attached.

[GeometryValidator_ErrorTraceback_12March2018.txt](https://github.com/peetw/GeometryValidator/files/1803110/GeometryValidator_ErrorTraceback_12March2018.txt)

**Comment by peetw** [comment]
@SteveLowman I actually encountered this exact situation a couple of days ago as well. When you installed QGIS using the OSGeo4W network installer, did you select "Express Desktop Install" or "Advanced Install"?

The shapely Python module can be installed by re-running the OSGeo4W network installer. On the first page, select "Advanced Install" and then on the packages page select the "python-shapely" package for installation (under the All -> Libs category). Alternatively, the shapely module is installed by default as part of the "qgis-full" or "qgis-ltr-full" meta packages under the All -> Desktop category (these create a similar installation to that of the standalone version).

**Comment by SteveLowman** [comment]
Thank you @peetw that is really useful info.
